### ISSUE TITLE
flex-basis must ouput a number with a unit (px, em,...) but the current implementation only outputs a number

### ISSUE THREAD

**Issue by tcoopman** [adam-r-kowalski/Elm-Css#8]
The current implementation of flex-basis takes a number but the specification requires a number + unit or a keyword (see https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis). So the current version is not usable.

**Comment by adam-r-kowalski** [comment]
Thanks, I changed the implementation to use pixels instead. Please reopen if it doesn't work for you.
